server {
	listen       80;
       location ^~ /apis {
              proxy_pass              http://127.0.0.1:8082;
              rewrite ^/apis& /;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              client_max_body_size    200m;
        }
		location ^~ /apis/DrawingPlane {
              proxy_pass              http://127.0.0.1:5004;
              rewrite ^/apis& /;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              client_max_body_size    200m;
        }

       #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
       location / {
           root   D:\kakj\project\outbust\dist;
           index  index.html index.htm;
           if (!-e $request_filename) {
                     rewrite ^(.*)$ /index.html?s=$1 last;
                     break;
             }
       }
}
server {
	listen       8610;
       location ^~ /apis {
              proxy_pass              http://127.0.0.1:9901;
              rewrite ^/apis& /;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              client_max_body_size    200m;
        }

       #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
       location / {
           root   D:\kakj\project\monitor\kd\dist;
           index  index.html index.htm;
           if (!-e $request_filename) {
                     rewrite ^(.*)$ /index.html?s=$1 last;
                     break;
             }
       }
}
server {
    listen       8810;
      
       #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
       location / {
           root   D:\wgai\dist;
           index  index.html index.htm;
       }

       location ^~ /jeecg-boot/ {
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin * always;
                add_header Access-Control-Allow-Methods 'GET,POST,PUT,DELETE,OPTIONS' always;
                add_header Access-Control-Allow-Headers 'Content-Type, X-Access-Token, tenant-id, Authorization, X-Requested-With' always;
                add_header Content-Length 0;
                add_header Content-Type text/plain;
                return 204;
            }
            add_header Access-Control-Allow-Origin * always;

            proxy_pass http://172.16.1.32:20001/jeecg-boot/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 200m;
        }
}
